version: 0.2

phases:
  install:
    commands:
      - echo Installing...
      - npm install -g serverless
      - npm install
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm test
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - serverless webpack
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - .webpack/service/*
